[WIP] Update docs to nhost-js-sdk v3
nhost/docs pull request #33
Opened 2021-02-14 13:08 UTC by nunopato

- update docs for the nhost-js-sdk v3 release

2021-02-22 17:29 UTC, elitan requested changes
Also, the current `code`-blocks look like links in dark mode.

2021-02-22 17:29 UTC, elitan commented on src/pages/libraries/nhost-js-sdk.mdx
> +| *clientStorage*            | ClientStorage | optional | Storage to use (defaults to `Window.localStorage`)                                      |   |
lower case on `Window`.

2021-02-22 17:29 UTC, elitan commented on src/pages/libraries/nhost-js-sdk.mdx
>  auth.changePassword(old_password, new_password);
`old_password` => `oldPassword`.

2021-02-22 17:39 UTC, nunopato commented on src/pages/libraries/nhost-js-sdk.mdx
> +| *clientStorage*            | ClientStorage | optional | Storage to use (defaults to `Window.localStorage`)                                      |   |
👍

2021-02-22 17:39 UTC, nunopato commented on src/pages/libraries/nhost-js-sdk.mdx
>  auth.changePassword(old_password, new_password);
👍

2021-02-24 09:24 UTC, elitan approved these changes

2021-03-01 12:47 UTC, merged